# Vectorizers

In [49]:
import scipy.sparse
import os
import pandas as pd
import numpy as np
from numpy import asarray
import matplotlib.pyplot as plt
import multiprocessing
import pickle

import gensim.downloader as api
from keras.preprocessing.text import Tokenizer
from sklearn.feature_extraction.text import TfidfVectorizer
from keras.utils import pad_sequences
from joblib import dump


NUM_of_CLASSES = 3
w2v_pretrained_model = "glove-twitter-100"
#w2v_pretrained_model = "glove-wiki-gigaword-100"
w2v_pretrained_model_filename = str(w2v_pretrained_model) + "-word2vec.txt" 

In [32]:
script_dir = os.path.dirname(os.path.abspath('vectorizer.ipynb'))
data_path = os.path.join(script_dir, 'Thesis_Jupyter_Final/src/')
os.getcwd()
print(data_path)

input_folder_path = os.path.join(data_path, 'input')
processed_folder_path = os.path.join(data_path, 'input/processed')
results_folder_path = "results"

# Create the folder if it doesn't exist
if not os.path.exists(results_folder_path):
    os.makedirs(results_folder_path)

/home2/s3985113/Thesis_Jupyter_Final/src/


In [20]:
def load_data(filename, process=True):
    # Load data
    data_file_path = os.path.join(input_folder_path, filename)
    df = pd.read_csv(data_file_path)

    x = df['x']
    y = df['y']

    return x, y

def load_vocab():
    vocab_data_filename = "vocab.pkl"
    file_path = os.path.join(processed_folder_path, vocab_data_filename)
    with open(file_path, 'rb') as f:
        vocab = pickle.load(f)
        vocab_size = len(vocab)

    vocab_size = len(vocab)

    return vocab, vocab_size
    

x_train, y_train = load_data("train.csv", process=False)
x_val, y_val = load_data("val.csv", process=False)
x_test, y_test = load_data("test.csv", process=False)

vocab, vocab_size = load_vocab()

In [21]:
def save_to_npz(matrix, file_path):
    scipy.sparse.save_npz(file_path, matrix)

def save_to_npy(arr, file_path):
    np.save(file_path, np.array(arr))

## TF-IDF

In [33]:
def get_tfidf_vectorizer(vocab, max_features, min_df, max_df):
    # Convert vocab to a dict in order to use it in TF-IDF vectorizer
    vocab_dict = {word: i for i, word in enumerate(vocab)}

    tfidf_vectorizer = TfidfVectorizer(
        max_features=max_features, # maximum number of features to keep, check unique vocabs and determine based on that, high causes saprse metrics and low value causes loss in important words/vocab
        vocabulary=vocab_dict,
        lowercase=False,
        ngram_range=(1, 3),  # range of n-grams,
        max_df=max_df,  # ignore terms that have a document frequency strictly higher than the threshold
        min_df=min_df,  # ignore terms that have a document frequency strictly lower than the threshold.
        use_idf=True,  # enable IDF weighting
        smooth_idf=True,  # smooth IDF weights --> provides stability, reduces run time errors
        sublinear_tf=True  # apply sublinear scaling to term frequencies
    )

    # Save tfidf vectorizer
    file_path = os.path.join(processed_folder_path, 'tfidf_vectorizer.joblib')
    dump(tfidf_vectorizer, file_path)

    return tfidf_vectorizer

def transform_to_tfidf(x_train, x_val, x_test):
    # Fit and transform the training set
    x_train_tfidf = tfidf_vectorizer.fit_transform(x_train)

    # Transform the validation and testing set
    x_val_tfidf = tfidf_vectorizer.transform(x_val)
    x_test_tfidf = tfidf_vectorizer.transform(x_test)

    # Save data
    save_to_npz(x_train_tfidf, os.path.join(processed_folder_path, "train_tfidf.npz"))
    save_to_npz(x_val_tfidf, os.path.join(processed_folder_path, "val_tfidf.npz"))
    save_to_npz(x_test_tfidf, os.path.join(processed_folder_path, "test_tfidf.npz"))

    return x_train_tfidf, x_val_tfidf, x_test_tfidf


max_features = 50000
max_df = 0.95
min_df = 5

tfidf_vectorizer = get_tfidf_vectorizer(vocab, max_features, min_df, max_df)
x_train_tfidf, x_val_tfidf, x_test_tfidf = transform_to_tfidf(x_train, x_val, x_test)
%store tfidf_vectorizer

print("\nData Shape (doc, vocab_size):\n* train: {}\n* validation: {}\n* test: {}\n".format(x_train_tfidf.shape, x_val_tfidf.shape, x_test_tfidf.shape))
print("x_train_tfidf:\n{}".format(x_train_tfidf))

Stored 'tfidf_vectorizer' (TfidfVectorizer)

Data Shape (doc, vocab_size):
* train: (41000, 12644)
* validation: (11532, 12644)
* test: (11905, 12644)

x_train_tfidf:
  (0, 10526)	0.3701578628181033
  (0, 4894)	0.32999433018072144
  (0, 2083)	0.29343888501321036
  (0, 1912)	0.2804613515563524
  (0, 1779)	0.2815241272434237
  (0, 1688)	0.24267616713297727
  (0, 1577)	0.27202940388432717
  (0, 734)	0.24386561416344335
  (0, 531)	0.21104954098373907
  (0, 388)	0.20404592571011101
  (0, 350)	0.2142543643095343
  (0, 287)	0.22160277130877745
  (0, 257)	0.2214904145041457
  (0, 173)	0.2183678200398483
  (0, 157)	0.1994293886378569
  (1, 3082)	0.5745930155556883
  (1, 1067)	0.4371293802225125
  (1, 1015)	0.48551153531743024
  (1, 761)	0.4929901829596753
  (2, 3892)	0.42134938973870983
  (2, 2887)	0.40702494790002386
  (2, 2474)	0.41414876264668526
  (2, 1363)	0.3570125709620734
  (2, 940)	0.3888075226900665
  (2, 468)	0.3431422543770557
  :	:
  (40996, 170)	0.13892466275358323
  (40996, 162)	

In [34]:
#TODO: delete
def save_tfidf_data(data, filename, feature_names):
    # Save the matrix with feature names as a DataFrame
    data = pd.DataFrame(data.toarray(), columns=feature_names)
    file_path = os.path.join(processed_folder_path, filename)
    data.to_csv(file_path, sep=',', index=False) # TODO: if this isn't working, note that you added sep=','


# Get feature names
feature_names = tfidf_vectorizer.get_feature_names_out()

# Save vectorized data
#save_tfidf_data(x_train_tfidf, "train_tfidf.csv", feature_names)
#save_tfidf_data(x_val_tfidf, "val_tfidf.csv", feature_names)

# Encode Data

In [35]:
def find_max_seq_len(data):
    # Find maximum sequence length
    max_seq_length = max([len(line.split()) for line in data])
    print(f'Maximum review length: {max_seq_length}')

    return max_seq_length

max_seq_length = find_max_seq_len(x_train)

Maximum review length: 476


In [39]:
def fit_tokenizer(data):
    # Fit tokenizer (on training data)
    tokenizer = Tokenizer()
    # Remove default filters, including punctuation
    tokenizer.filters = ""  
    # Disable lowercase conversion
    tokenizer.lower = False  
    tokenizer.fit_on_texts(data) 

    return tokenizer

def encode_text(lines, tokenizer, max_length, filename):
    # Integer encode
    encoded_seq = tokenizer.texts_to_sequences(lines)
    # Pad the encoded sequences
    padded = pad_sequences(encoded_seq, maxlen=max_length, padding='post')

    # Save to np.array
    save_to_npy(padded, os.path.join(processed_folder_path, filename))

    return padded
    
    
tokenizer = fit_tokenizer(x_train)

# Encode Data
x_train_encoded = encode_text(x_train, tokenizer, max_seq_length, "train_encoded_x.npy")
x_val_encoded = encode_text(x_val, tokenizer, max_seq_length, "val_encoded_x.npy")
x_test_encoded = encode_text(x_test, tokenizer, max_seq_length, "test_encoded_x.npy")

print("\nEncoded Data Shape (doc, vocab_size):\n* train: {}\n* validation: {}\n* test: {}\n".format(x_train_encoded.shape, x_val_encoded.shape, x_test_encoded.shape))
print("x_train_tfidf:\n{}".format(x_train_encoded))


Encoded Data Shape (doc, vocab_size):
* train: (41000, 476)
* validation: (11532, 476)
* test: (11905, 476)

x_train_tfidf:
[[ 269  759 1670 ...    0    0    0]
 [ 942  806 2151 ...    0    0    0]
 [2101  172  615 ...    0    0    0]
 ...
 [ 132  170  425 ...    0    0    0]
 [1983  645  161 ...    0    0    0]
 [ 232  205  222 ...    0    0    0]]


### Encode y

In [40]:
# TODO: can't remember if this is used somewhere else, if not save data inside function
def one_hot_encode(y):
    y_encoded = np.zeros((len(y), NUM_of_CLASSES))
    for i, label in enumerate(y):
        y_encoded[i, label - 1] = 1

    return y_encoded

# Convert sentiment labels to one-hot encoding
y_train_encoded = one_hot_encode(y_train)
y_val_encoded = one_hot_encode(y_val)
y_test_encoded = one_hot_encode(y_test)

# Save y-encoded sets
save_to_npy(y_train_encoded, os.path.join(processed_folder_path, "train_encoded_y.npy"))
save_to_npy(y_val_encoded, os.path.join(processed_folder_path, "val_encoded_y.npy"))
save_to_npy(y_test_encoded, os.path.join(processed_folder_path, "test_encoded_y.npy"))
   
print("\ny-Encoded Data Shape:\n* train: {}\n* validation: {}\n* test: {}\n".format(y_train_encoded.shape, y_val_encoded.shape, y_test_encoded.shape))


y-Encoded Data Shape:
* train: (41000, 3)
* validation: (11532, 3)
* test: (11905, 3)



# Word2Vec

In [42]:
# Total vocabulary size plus 0 for unknown words
embedding_vocab_size = len(tokenizer.word_index) + 1
print("embedding_vocab_size: ", embedding_vocab_size)

# Check if there are any words identified via the tokenizer that are not in vocab
tokenizer_vocab = set(tokenizer.word_index.keys())
vocab_set = set(vocab)
tokenizer_only_words = tokenizer_vocab.difference(vocab_set)
print("Words in tokenizer but not in vocab: ", len(tokenizer_only_words))

embedding_vocab_size:  12466
Words in tokenizer but not in vocab:  0


In [50]:
def load_embedding():
    w2v_pretrained_file_path = os.path.join(processed_folder_path, w2v_pretrained_model_filename)
    if not os.path.exists(w2v_pretrained_file_path):
        # Check if the pre-trained Word2Vec model is already downloaded. If not, download it.
        print("\nW2v model doesn't exist")
        model = api.load(w2v_pretrained_model)
        model.save_word2vec_format(w2v_pretrained_file_path, binary=False)
        # 5186/12465 (41.60%) are not defined with twitter-glove
        # 5177/12465 (41.53%) are not defined with wiki

    # Load embedding into memory, skip first line
    print("Loading w2v model...")
    file = open(w2v_pretrained_file_path, 'r', encoding='utf8')
    lines = file.readlines()[1:]
    file.close()

    # Create a map of words to vectors
    embedding = dict()
    for line in lines:
        parts = line.split()
        # Set key as string word, value as numpy array for vector
        embedding[parts[0]] = asarray(parts[1:], dtype='float32')

    return embedding

def get_emb_matrix(loaded_embedding, tokenizer, embedding_dim):
    # Create a weight matrix for the Embedding layer from a loaded/pretrained embedding

    # Define weight matrix dimensions (vocab_size + 1 for unknown words) with all 0 
    emb_matrix = np.zeros((len(tokenizer.word_index) + 1, embedding_dim))

    count_all_words = 0
    count_na_words = 0
    zero_vector_words = []
    for word, i in tokenizer.word_index.items():
        # Map loaded vectors to terms in vocab
        if word in loaded_embedding.keys():
            emb_matrix[i] = loaded_embedding.get(word)
        else:
            # Some terms such as emojis or neg-tagged words are not found in the loaded w2v model, hence they will have vectors with all 0
            zero_vector_words.append(word)
            count_na_words += 1
        count_all_words += 1
    print(f'{count_na_words}/{count_all_words} ({((count_na_words/count_all_words)*100):.2f}%) are not defined in the pretrained W2V model and will receive vectors with all 0.')
    print(f"W2V Embedding Matrix shape: {emb_matrix.shape}")
    print(f"Embedding Matrix:\n{emb_matrix[:10, :6]}")

    # Save unrecognized words that are not present in the GloVe model
    file_path = os.path.join(processed_folder_path, "out_of_glove_words.txt")
    with open(file_path, 'w') as file:
        file.write('\n'.join(zero_vector_words))

    # Save embeddings
    # TODO: delete
    file_path = os.path.join(processed_folder_path, "embedding_matrix.txt")
    with open(file_path, 'w') as file:
        file.write('\n'.join(' '.join(str(x) for x in row) for row in emb_matrix))

    # TODO: keep
    save_to_npy(emb_matrix, (os.path.join(processed_folder_path, "embedding_matrix.npy")))
    
    return emb_matrix

pretrained_embedding = load_embedding()
embedding_dim = 100
w2v_embedding_vectors = get_emb_matrix(pretrained_embedding, tokenizer, embedding_dim)

Loading w2v model...
5186/12465 (41.60%) are not defined in the pretrained W2V model and will receive vectors with all 0.
W2V Embedding Matrix shape: (12466, 100)
Embedding Matrix:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
